// src/forms/rtp/api.ts
// RTP submission flow:
//   1. POST /_api/gcp_projectses  — inactive stub project, bound to the
//      selected Company (Account) via `gcp_Company@odata.bind`.
//   2. POST /_api/gcp_requests    — parent request row, bound to the project
//      from (1) via `gcp_Project@odata.bind` and to the Company.
//   3. POST /_api/gcp_rtprequests — RTP details row, bound to (2) via
//      `gcp_Request@odata.bind = /gcp_requests(<id>)`.

import {
  createProject,
  getProjectById,
} from '../../shared/services/projectService';
import { createRequest } from '../../shared/services/requestService';
import { createRtpRequest } from '../../shared/services/rtpRequestService';
import { serializeDocuments } from '../../shared/documents';
import type { DocumentLink } from '../../shared/documents';
import type { CreateGcpProjectInput } from '../../types/project';
import type { CreateGcpRequestInput } from '../../types/request';
import type {
  CreateGcpRtpRequestInput,
  FormTypeValue,
} from '../../types/rtpRequest';
import type { SoaCodeValue } from '../../data/soaChoices';
import type { RtpFormState } from './types';

type SubmitResult = {
  requestId: string;
  rtpRecordId: string;
  projectId: string;
};

// Initial gcp_projectstatus for the stub project created at request time.
// 0 = "inactive" per the user's data model.
const PROJECT_STATUS_INACTIVE = 0;

// Map the RTP matter (RTP code) → SOA code (also code "RTP" → value 1).
// soaCodeChoices already aligns labels to codes, so we use the label of the matter.
const resolveSoaCodeForRtp = (): SoaCodeValue => 1; // "RTP"

// `gcp_formtype` on gcp_rtprequest has a single option: 1 = "RTP form".
const RTP_FORM_TYPE: FormTypeValue = 1;

type SubmitRtpOptions = {
  /** Logged-in user's contact GUID for the gcp_RequestorName lookup. The form's
   *  `requestorContactId` field holds an email (used only for the UI select), so
   *  the real contact GUID must be passed here — otherwise the contact lookup is
   *  skipped and the Contact-scoped table permission denies later associations. */
  requestorContactId?: string | null;
  /** Uploaded document links to persist on the request's gcp_documentsurl. */
  documents?: DocumentLink[];
};

const submitRtpRequest = async (
  data: RtpFormState,
  options: SubmitRtpOptions = {}
): Promise<SubmitResult> => {
  // `data.companyId` is now an Account GUID (set by the Company picker in
  // step 1). Treat empty string as no binding.
  const companyAccountId = data.companyId || null;

  // Step 1 — create the stub project record bound to the selected Company.
  const projectInput: CreateGcpProjectInput = {
    gcp_projectname: data.projectName || null,
    gcp_projectstatus: PROJECT_STATUS_INACTIVE,
  };
  const projectCreated = await createProject(projectInput, {
    companyAccountId,
  });

  // `gcp_projectcode` is an auto-number generated by Dataverse on the project
  // record. The parent gcp_request keeps its own gcp_projectcode column (which
  // the detail page reads), so we must copy the generated code across — the
  // lookup alone doesn't surface it. Prefer the create representation; fall
  // back to a fetch in case the auto-number wasn't returned inline.
  let projectCode = projectCreated.record?.code ?? null;
  if (!projectCode) {
    const fetched = await getProjectById(projectCreated.id);
    projectCode = fetched?.code ?? null;
  }

  const parentInput: CreateGcpRequestInput = {
    gcp_category: data.categoryValue,
    gcp_mattertype: data.matterValue,
    gcp_soacode: resolveSoaCodeForRtp(),
    gcp_requestoremail: data.requestorEmail || null,
    gcp_project_name: data.projectName || null,
    gcp_projectcode: projectCode,
    gcp_projectdiscription: data.projectDescription || null,
    gcp_acknowledgement: data.acknowledged,
    gcp_submittedon: new Date().toISOString(),
    // New requests start in status "New" (1) per requestStatusChoices.
    gcp_requeststatus: 1,
    gcp_documentsurl: serializeDocuments(options.documents ?? []),
  };

  // The logged-in user's contact GUID arrives via `options.requestorContactId`
  // (the form's `data.requestorContactId` holds only an email). Binding
  // gcp_RequestorName here makes the user the owner of the parent request, which
  // the Contact-scoped table permission requires for the child association below.
  const created = await createRequest(parentInput, {
    lookups: {
      requestorContactId: options.requestorContactId || null,
      companyAccountId,
      projectId: projectCreated.id,
    },
  });

  // Step 2 — POST the gcp_rtprequest child row, bound to the parent gcp_request
  // via the case-sensitive `gcp_Request@odata.bind` navigation property
  // (PhysicalName from customizations.xml).
  //
  // Logical-name mapping (verified against customizations.xml):
  //   data.clientName         → gcp_client_name_text  (nvarchar, "Client Name")
  //   data.projectName        → gcp_projectname       (nvarchar)
  //   data.projectDescription → gcp_projectdescription (ntext)
  //   data.registrationType   → gcp_registrationtype  (picklist, OptionSet gcp_registrationtype)
  //   data.tenderClosingDate  → gcp_tenderclosingdate (datetime, DateOnly behavior=3)
  //   data.acknowledged       → gcp_acknowledgement   (bit, required on table)
  //   data.specialProjectFlag → gcp_specialproject    (bit)
  //   data.requestorEmail     → gcp_requesteremail    (nvarchar, "Requester Email" — note the
  //                                                    rtprequest table uses *requester*, not
  //                                                    *requestor* as on the parent gcp_request)
  //   data.categoryValue      → gcp_category          (mirrors parent)
  //   data.matterValue        → gcp_matters           (picklist, shared OptionSet gcp_matters)
  //
  // `gcp_specialprojectwithapprovedwaiver` and `gcp_verifiercomments` are not
  // captured by this form and are left for back-office update later.
  const rtpInput: CreateGcpRtpRequestInput = {
    gcp_client_name_text: data.clientName || null,
    gcp_projectname: data.projectName || null,
    gcp_projectdescription: data.projectDescription || null,
    gcp_requesteremail: data.requestorEmail || null,
    gcp_category: data.categoryValue,
    gcp_matters: data.matterValue,
    gcp_formtype: RTP_FORM_TYPE,
    gcp_registrationtype:
      data.registrationType === '' ? null : data.registrationType,
    gcp_tenderclosingdate: data.tenderClosingDate || null,
    gcp_acknowledgement: data.acknowledged,
    gcp_specialproject: data.specialProjectFlag,
    // Match the parent request's initial status ("New" = 1).
    gcp_requeststatus: 1,
  };

  const rtpCreated = await createRtpRequest(rtpInput, {
    lookups: {
      requestId: created.id,
      companyAccountId,
      // Same contact GUID as the parent request, for symmetry with that flow.
      requesterContactId: options.requestorContactId || null,
    },
  });

  return {
    requestId: created.id,
    rtpRecordId: rtpCreated.id,
    projectId: projectCreated.id,
  };
};

export { submitRtpRequest };
export type { SubmitResult, SubmitRtpOptions };
